# **NumPy ile Keşifçi Veri Analizi (EDA)**

NumPy, Python'da bilimsel hesaplamalar yapmak için kullanılan güçlü bir kütüphanedir. Özellikle çok boyutlu diziler ve matrislerle çalışmak için tasarlanmıştır ve matematiksel fonksiyonlar sağlar. 

In [2]:
import numpy as np #kütüphanemizi projemize import ettik.

**NumPy'da Diziler**

In [3]:
listem = [1,2,3,4,5]
type(listem) #dizimiz liste tipindedir.

list

In [5]:
listem = np.array(listem) #numpy dizisine dönüştürdük.
print(listem.ndim)

1


In [10]:
#çok boyutlu numpy dizisi oluşturma:
ikiBoyutluDizi = np.array([ [1,2,3], [4,5,6] ]) 
ikiBoyutluDizi

array([[1, 2, 3],
       [4, 5, 6]])

**Diziler üzerinde temel işlemler**

In [46]:
yeniDizi1 = np.arange(0,10)
#TOPLAMA :
print( f" Dizideki elemanların toplamı: {yeniDizi1.sum()}"  )

 Dizideki elemanların toplamı: 45


In [47]:
yeniDizi2 = np.arange(0,10)
#ORTALAMA :
print( f" Dizideki elemanların ortalaması: {yeniDizi2.mean()}"  )

 Dizideki elemanların ortalaması: 4.5


In [48]:
yeniDizi3 = np.arange(0,10)
#MAKSİMUM :
print( f" Dizideki elemanların EN BÜYÜĞÜ: {yeniDizi3.max()}"  )

 Dizideki elemanların EN BÜYÜĞÜ: 9


In [51]:
yeniDizi4 = np.arange(0,10)
#STANDART SAPMA :
print( f" Dizideki elemanların standart sapması: {yeniDizi4.std()}"  )

 Dizideki elemanların standart sapması: 2.8722813232690143


In [11]:
#diziyi tersine çevirmek:
listem[::-1]

array([5, 4, 3, 2, 1])

**Çeşitli dizileri oluşturma yöntemleri**

In [16]:
#arange(<başlangıç>, <bitiş>, <kaç farkla artacak>) 
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [79]:
#np.zeros(x) -> x adet 0'dan oluşan dizi :
np.zeros(5, dtype = int)

array([0, 0, 0, 0, 0])

In [80]:
#np.ones(y) -> y adet 1'den oluşan dizi :
np.ones(7, dtype = int)

array([1, 1, 1, 1, 1, 1, 1])

In [11]:
np.full ((3,3),5) #3x3'lük, 5 sayısından oluşan matris

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [20]:
# np.linspace(a,b,c) -> a ile b arasında, eşit aralıklı c adet sayı içeren dizi :
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [13]:
# np.eye(z) -> z*z'lik köşegen matrisi oluşturmak :
np.eye(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [23]:
# np.random.randn(a) -> a adet rastgele değerden oluşan dizi :
np.random.randn(5)

array([ 0.12420491, -0.68691951,  1.37884867, -0.46895696,  1.60641438])

In [29]:
# np.random.randint(b,c,d) -> b ile c arasında rastgele d adet sayı döndürmek :
np.random.randint(4,9,10)

array([5, 4, 5, 5, 5, 8, 6, 6, 7, 4])

In [36]:
# 0-40 arası değerlerden oluşan diziyi 4 sütun-10 satıra bölmek :
dizim = np.arange(0,40)
dizim.reshape(4,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

**NumPy'da Indexleme**

In [56]:
benimDizim = np.arange(0,15)
benimDizim[3] # yoluyla istenilen elemana erişilir.

3

In [60]:
#benimDizim[a:b] -> a'dan b'ye kadar olan elemanları basar. (a dahil,b değil)
benimDizim[3:7]

array([3, 4, 5, 6])

**Slicing İşlemi**

In [14]:
baskaDizi = np.arange(0,24)
slicingDizisi = baskaDizi[4:9]
slicingDizisi[:] = 700
slicingDizisi
#2. satırda seçtiğimiz aralıkta bulunan elemanları 3. satırda verdiğimiz değerle değiştirebiliriz.

array([700, 700, 700, 700, 700])

In [15]:
baskaDizi

array([  0,   1,   2,   3, 700, 700, 700, 700, 700,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23])